import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
	return (
		<nav className="flex w-full items-center justify-between border-b p-4 font-semibold text-xl">
			<div>
				<img
					src={"/CWRU_Linux_Club_horizontal_transparent.svg"}
					alt={"cwru linux club logo"}
					style={{ filter: "invert(1)" }}
					className="h-12 w-auto"
				/>
			</div>

			<div>
				<a
					href={"https://discord.gg/y8qm7YUW5F"}
					target="_blank"
					rel="noopener noreferrer"
				>
					<img
						src={"/Discord-Logo-White.png"}
						alt="Discord link"
						className="h-6 w-auto"
					/>
				</a>
			</div>

			<div>Sign In</div>
		</nav>
	);
}

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={"${inter.variable} flex flex-col gap-4 font-sans"}>
				<TopNav />
				{children}
			</body>
		</html>
	);
}
